version: '3.8'

services:
  db:
    container_name: db_wallet_service
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '${DB_PORT}:5433'

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 10s
      retries: 5
    volumes:
      - user_service_db_data:/var/lib/postgresql/data

  backend:
    container_name: user_wallet_service
    depends_on:
      db:
        condition: service_healthy
    build: .
    command: ./main
    ports:
      - '8000:8000'
    env_file:
      - .env

volumes:
  user_service_db_data:
